name = "Dataverse"
uuid = "9c0b9be8-e31e-490f-90fe-77697562404d"
authors = ["gaelforget <gforget@mit.edu> and contributors"]
version = "0.1.0"

[deps]
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Downloads = "f43a241f-c20a-4ad4-852c-f6b1247861c6"
OceanStateEstimation = "891f6deb-a4f5-4bc5-a2e3-1e8f649cdd2c"

[compat]
julia = "1"
CSV = "0.10"
DataFrames = "1"
OceanStateEstimation = "0.2"
